"""
Alembic migration environment.

Configured for:
- Async PostgreSQL+TimescaleDB in production
- Synchronous SQLite in local development (for migration execution)
- include_object() filter prevents TimescaleDB internal indexes from
  being dropped by autogenerated migrations (Pitfall 3 from RESEARCH.md)
"""
import asyncio
import sys
import os
from logging.config import fileConfig

from sqlalchemy import pool, engine_from_config
from sqlalchemy.ext.asyncio import create_async_engine

from alembic import context

# Add backend/ to path so we can import app modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.core.config import settings
from app.models.market_data import Base
from app.models.signal import TradingSignal  # noqa: F401  — registers with Base.metadata

# Alembic Config object
alembic_config = context.config

# Set the database URL from our settings
alembic_config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Set up logging
if alembic_config.config_file_name is not None:
    fileConfig(alembic_config.config_file_name)

# Target metadata for autogenerate support
target_metadata = Base.metadata


def include_object(object, name, type_, reflected, compare_to):
    """
    Filter out TimescaleDB-managed indexes to prevent autogenerate from
    dropping them (Pitfall 3: Alembic Drops TimescaleDB's Hypertable Index).

    Without this filter, running `alembic revision --autogenerate` after
    the initial hypertable migration would produce a migration that drops
    TimescaleDB's internal indexes, breaking the hypertable.
    """
    if type_ == "index" and reflected and compare_to is None:
        return False  # skip TimescaleDB-managed indexes
    return True


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode (no DB connection).

    Emits SQL to stdout/file instead of executing it.
    Useful for reviewing migrations before applying them.
    """
    url = alembic_config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode (with live DB connection).

    For SQLite (dev): uses synchronous engine directly.
    For PostgreSQL (prod): uses synchronous psycopg2 driver for migrations
    (asyncpg is for runtime only; Alembic needs synchronous access).
    """
    db_url = settings.DATABASE_URL

    # For migration execution, convert async URLs to synchronous equivalents
    # asyncpg -> psycopg2 for PostgreSQL migrations
    # aiosqlite -> standard sqlite for SQLite migrations
    sync_url = db_url.replace(
        "postgresql+asyncpg://", "postgresql+psycopg2://"
    ).replace(
        "sqlite+aiosqlite://", "sqlite://"
    )

    connectable = engine_from_config(
        {"sqlalchemy.url": sync_url},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
